name: Main Workflow

on:
  push:
    branches:
      - "master"
      - "develop"

jobs:
  sonar_client:
    name: Test - SonarCloud Scan Client
    runs-on: ubuntu-18.04
    needs: [test_client, test_cito]
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.4
      - name: SonarCloud Scan
        working-directory: client
        run: mvn -B clean verify -Psonar -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
